version: '3'

services:
  t-postgres-boilerplate:
    container_name: 't-workplus-postgres'
    image: 'postgres:13.2'
    restart: always
    command: postgres -c log_destination=stderr -c log_statement=all
    ports:
      - '15432:5432'
    volumes:
      - t-boilerplate-postgres-volume:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=${TEST_POSTGRES_USER}"
      - "POSTGRES_DB=${TEST_POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}"
  t-redis-boilerplate:
    container_name: 't-workplus-redis'
    image: 'redis:latest'
    ports:
      - '16379:6379'
    volumes:
      - t-boilerplate-redis-volume:/data
volumes:
  t-boilerplate-postgres-volume:
  t-boilerplate-redis-volume:
