version: '3'

services:
  # TODO: CLionのdebug機能を使いたい場合はコメントアウト
  #  app-boilerplate:
  #    container_name: boilerplate
  #    build:
  #      context: .
  #      dockerfile: "dev.dockerfile"
  #    restart: always
  #    expose:
  #      - 8080
  #    ports:
  #      - 8080:8080
  #    tty: true
  boilerplate-postgres:
    container_name: 'boilerplate-postgres'
    image: 'postgres:latest'
    restart: always
    command: postgres -c log_destination=stderr -c log_statement=all
    expose:
      - 5432
    ports:
      - '5432:5432'
    volumes:
      - boilerplate-postgres-volume:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
  boilerplate-redis:
    container_name: 'boilerplate-redis'
    image: 'redis:latest'
    expose:
      - 6379
    ports:
      - '6379:6379'
    volumes:
      - boilerplate-redis-volume:/data
  boilerplate-swagger-editor:
    container_name: 'boilerplate-swagger-editor'
    image: swaggerapi/swagger-editor
    ports:
      - "8081:8080"
    volumes:
      - ./swagger:/swagger
    environment:
      SWAGGER_FILE: /swagger/swagger.yaml
  boilerplate-swagger-ui:
    container_name: 'boilerplate-swagger-ui'
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8080"
    volumes:
      - ./swagger/swagger.yaml:/swagger.yaml
    environment:
      SWAGGER_JSON: /swagger.yaml
volumes:
  boilerplate-postgres-volume:
  boilerplate-redis-volume:
