version: '3.9'

services:
  # TODO: CLionのdebug機能を使いたい場合はコメントアウト
  #  d-boilerplate-app:
  #    container_name: d-boilerplate
  #    image: boilerplate
  #    #    build:
  #    #      context: .
  #    #      dockerfile: 'dev.dockerfile'
  #    ports:
  #      - ${DC_APP_BOUND_PORT}:8080
  #    tty: true
  #    networks:
  #      - d-boilerplate-network
  #    environment:
  #      - "DB_URL=${DB_URL}"
  #      - "REDIS_ADDRESS=${REDIS_ADDRESS}"
  #      - "REDIS_COOKIE_SESSION_PRIVATE_KEY=${REDIS_COOKIE_SESSION_PRIVATE_KEY}"
  #      - "FRONTEND_ORIGIN=${FRONTEND_ORIGIN}"
  #      - "VALID_REFERER_VALUE=${VALID_REFERER_VALUE}"
  #      - "VALID_ORIGIN_VALUE=${VALID_ORIGIN_VALUE}"
  #      - "APP_BOUND_ADDRESS=${APP_BOUND_ADDRESS}"
  #      - "RUST_LOG=${RUST_LOG}"
  #      - "RUST_BACKTRACE=${RUST_BACKTRACE}"
  d-boilerplate-postgres:
    container_name: d-boilerplate-postgres
    image: postgres:latest
    command: postgres -c log_destination=stderr -c log_statement=all
    ports:
      - '${DC_DB_PORT}:5432'
    volumes:
      - d-boilerplate-postgres-volume:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=${DC_DB_NAME}"
      - "POSTGRES_USER=${DC_DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DC_DB_PASSWORD}"
    networks:
      - d-boilerplate-network
  d-boilerplate-redis:
    container_name: 'd-boilerplate-redis'
    image: redis:latest
    ports:
      - '${DC_REDIS_PORT}:6379'
    volumes:
      - d-boilerplate-redis-volume:/data
    networks:
      - d-boilerplate-network
  d-boilerplate-swagger-editor:
    container_name: 'd-boilerplate-swagger-editor'
    image: swaggerapi/swagger-editor
    ports:
      - '8081:8080'
    volumes:
      - ./swagger:/swagger
    environment:
      SWAGGER_FILE: /swagger/swagger.yaml
    networks:
      - d-boilerplate-swagger-network
  d-boilerplate-swagger-ui:
    container_name: 'd-boilerplate-swagger-ui'
    image: swaggerapi/swagger-ui
    ports:
      - '8082:8080'
    volumes:
      - ./swagger/swagger.yaml:/swagger.yaml
    environment:
      SWAGGER_JSON: /swagger.yaml
    networks:
      - d-boilerplate-swagger-network

volumes:
  d-boilerplate-postgres-volume:
  d-boilerplate-redis-volume:

networks:
  d-boilerplate-network:
    name: d-boilerplate-network
    driver: bridge
  d-boilerplate-swagger-network:
    name: d-boilerplate-swagger-network
    driver: bridge
