version: '3.9'

services:
  t-boilerplate-postgres:
    container_name: t-boilerplate-postgres
    image: postgres:latest
    command: postgres -c log_destination=stderr -c log_statement=all
    ports:
      - '${TEST_DC_DB_PORT}:5432'
    volumes:
      - t-boilerplate-postgres-volume:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=${TEST_DC_DB_NAME}"
      - "POSTGRES_USER=${TEST_DC_DB_USERNAME}"
      - "POSTGRES_PASSWORD=${TEST_DC_DB_PASSWORD}"
    networks:
      - t-boilerplate-network
  t-boilerplate-redis:
    container_name: t-boilerplate-redis
    image: redis:latest
    ports:
      - '${TEST_DC_REDIS_PORT}:6379'
    volumes:
      - t-boilerplate-redis-volume:/data
    networks:
      - t-boilerplate-network

volumes:
  t-boilerplate-postgres-volume:
  t-boilerplate-redis-volume:

networks:
  t-boilerplate-network:
    name: t-boilerplate-network
    driver: bridge
